version: '3.8'

services:
  # Veritabanı Servisi
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: person_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Backend Servisi
  backend:
    build: ./backend
    ports:
      - "3000:3000"  # Bilgisayarındaki 3000 -> Docker içindeki 3000
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/person_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3001:3001" # Bilgisayarındaki 3001'i Docker'daki 3001'e bağlar
    environment:
      - PORT=3001
    stdin_open: true
    tty: true